image: "python:3.8-buster"

stages:
  - tox
  - package

tox:
  stage: "test"
  script:
    - pip install tox
    - tox

package:
  stage: "package"
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.whl


