image: "python:3.8-buster"

stages:
  - tox
  - publish

before_script:
  - >
    export DOCKER_REGISTRY_ROBOT_ACCESS_KEY=$(
    echo $DOCKER_REGISTRY_ROBOT_ACCESS_KEY | base64 -d)
  - >
    export DOCKER_REGISTRY_ROBOT_NAME=$(
    echo $DOCKER_REGISTRY_ROBOT_NAME | base64 -d)

tox:
  stage: tox
  script:
    - pip install tox
    - tox
  artifacts:
    paths:
      - badges
      - docs/_build
      - htmlcov
      - pylint.html

package:
  stage: publish
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist

pages:
  stage: publish
  dependencies:
    - tox
  script:
    - mv docs/_build/html/* public/docs
    - mv pylint.html public/pylint/index.html
    - mv htmlcov/* public/coverage
  artifacts:
    paths:
    - public
  only:
    - develop
